site_name: Gregory Ashton
site_url: https://www.GregoryAshton.github.io
site_author: Gregory Ashton
site_dir: docs/
docs_dir: source/
repo_url: https://github.com/GregoryAshton/GregoryAshton.github.io
nav:
    - Home: index.md
    - Science: science.md
    - Group: group.md
    - Projects: projects.md
    - Help: help.md
    - Notes: notes.md
plugins:
    - search
    - macros
extra_javascript:
    - js/goatcounter.js
theme: cinder
markdown_extensions:
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - md_in_html
